export const pathDefault = {
  homePage: "/",
  admin: "/admin",
  managerUser: "/admin/manager-user",
  managerReservation: "/admin/manager-reservation",
  managerComments: "/admin/manager-comments",
  managerRoom: "/admin/manager-room",
  managerLocation: "/admin/manager-location",
  adminLogin: "/admin-login",
  profileAdmin: "/admin/admin-profile",
  roomList: "/room-list/:id",
  roomDetail: "/room-detail/:id",
  signIn: "/sign-in",
  signUp: "/sign-up",
  infoUser: "/info-user",
};
